DROP TABLE IF EXISTS alumno_modulo CASCADE;
DROP TABLE IF EXISTS calificaciones CASCADE;
DROP TABLE IF EXISTS expedientes CASCADE;
DROP TABLE IF EXISTS alumnos CASCADE;
DROP TABLE IF EXISTS modulos CASCADE;

-- Tabla alumnos (incluye Persona)
CREATE TABLE IF NOT EXISTS alumnos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellidos VARCHAR(50) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    edad INT NOT NULL,
    nacionalidad VARCHAR(50) NOT NULL,
    fecha_incorporacion DATE NOT NULL,
    nota_media DOUBLE NOT NULL,
    faltas INT DEFAULT 0,
    retrasos INT DEFAULT 0,
    partes INT DEFAULT 0
);

-- Tabla modulos
CREATE TABLE IF NOT EXISTS modulos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    siglas VARCHAR(10) NOT NULL,
    horas INT NOT NULL
);

-- Tabla intermedia: alumno_modulo (relación N:N)
CREATE TABLE IF NOT EXISTS alumno_modulo (
    id_alumno BIGINT NOT NULL,
    id_modulo BIGINT NOT NULL,
    PRIMARY KEY (id_alumno, id_modulo),
    FOREIGN KEY (id_alumno) REFERENCES alumnos(id) ON DELETE CASCADE,
    FOREIGN KEY (id_modulo) REFERENCES modulos(id) ON DELETE CASCADE
);

-- Tabla expediente
CREATE TABLE IF NOT EXISTS expedientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_alumno BIGINT NOT NULL UNIQUE,
    nota_media DOUBLE NOT NULL,
    observaciones VARCHAR(255),
    FOREIGN KEY (id_alumno) REFERENCES alumnos(id) ON DELETE CASCADE
);

-- Tabla calificaciones
CREATE TABLE IF NOT EXISTS calificaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_expediente BIGINT NOT NULL,
    modulo_siglas VARCHAR(10) NOT NULL,
    nota DOUBLE NOT NULL,
    FOREIGN KEY (id_expediente) REFERENCES expedientes(id) ON DELETE CASCADE
);
